### ISSUE TITLE
test.py fails

### ISSUE THREAD

**Issue by Mattyboi123** [HITS-MBM/conan#5]
Hello, I have just installed conan on a linux-breathing machine and ran the test.py script from the terminal.
It found gromacs, mencoder and gnuplot OK (after I installed them) but seems not to find any of the .dat files (although they are present) subsequently it fails to pass the test and suggests that conan will not run at all.

Here is the complete (long) output

Welcome to the CONAN test script. Fingers crossed!
Checking for gmx_2019...FOUND
Checking for mencoder...FOUND
Checking for gnuplot...FOUND
This file doesn't exist at all: aggregate/local_interactions.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/local_interactions.dat, file_b: aggregate/local_interactions.dat, errors:-1
This file doesn't exist at all: aggregate/time_mdmat_rmsd.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/time_mdmat_rmsd.dat, file_b: aggregate/time_mdmat_rmsd.dat, errors:-1
This file doesn't exist at all: aggregate/timeline.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/timeline.dat, file_b: aggregate/timeline.dat, errors:-1
This file doesn't exist at all: aggregate/native_contacts.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/native_contacts.dat, file_b: aggregate/native_contacts.dat, errors:-1
This file doesn't exist at all: aggregate/mdmat_average_rmsf.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/mdmat_average_rmsf.dat, file_b: aggregate/mdmat_average_rmsf.dat, errors:-1
This file doesn't exist at all: matrices/00010.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00010.dat, file_b: matrices/00010.dat, errors:-1
This file doesn't exist at all: matrices/00008.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00008.dat, file_b: matrices/00008.dat, errors:-1
This file doesn't exist at all: matrices/00000.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00000.dat, file_b: matrices/00000.dat, errors:-1
This file doesn't exist at all: matrices/00006.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00006.dat, file_b: matrices/00006.dat, errors:-1
This file doesn't exist at all: matrices/00005.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00005.dat, file_b: matrices/00005.dat, errors:-1
This file doesn't exist at all: matrices/00002.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00002.dat, file_b: matrices/00002.dat, errors:-1
This file doesn't exist at all: matrices/00001.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00001.dat, file_b: matrices/00001.dat, errors:-1
This file doesn't exist at all: matrices/00009.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00009.dat, file_b: matrices/00009.dat, errors:-1
This file doesn't exist at all: matrices/00003.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00003.dat, file_b: matrices/00003.dat, errors:-1
This file doesn't exist at all: matrices/00007.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00007.dat, file_b: matrices/00007.dat, errors:-1
This file doesn't exist at all: matrices/00004.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00004.dat, file_b: matrices/00004.dat, errors:-1
Test 1: I/O, Result: FAILED
Removing files from old tests...
This file doesn't exist at all: aggregate/pearson_data_obs_1.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/pearson_data_obs_1.dat, file_b: aggregate/pearson_data_obs_1.dat, errors:-1
This file doesn't exist at all: aggregate/pearson_map_density.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/pearson_map_density.dat, file_b: aggregate/pearson_map_density.dat, errors:-1
This file doesn't exist at all: aggregate/pearson_data.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/pearson_data.dat, file_b: aggregate/pearson_data.dat, errors:-1
Test 2: Correlation analysis... FAILED
This file doesn't exist at all: cluster_trj/rmsd_interframe.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/rmsd_interframe.dat, file_b: cluster_trj/rmsd_interframe.dat, errors:-1
This file doesn't exist at all: cluster_trj/2/assignment.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/2/assignment.dat, file_b: cluster_trj/2/assignment.dat, errors:-1
This file doesn't exist at all: cluster_trj/2/cluster1/lifetime.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/2/cluster1/lifetime.dat, file_b: cluster_trj/2/cluster1/lifetime.dat, errors:-1
This file doesn't exist at all: cluster_trj/2/cluster1/average_map.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/2/cluster1/average_map.dat, file_b: cluster_trj/2/cluster1/average_map.dat, errors:-1
This file doesn't exist at all: cluster_trj/2/cluster0/lifetime.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/2/cluster0/lifetime.dat, file_b: cluster_trj/2/cluster0/lifetime.dat, errors:-1
This file doesn't exist at all: cluster_trj/2/cluster0/average_map.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/2/cluster0/average_map.dat, file_b: cluster_trj/2/cluster0/average_map.dat, errors:-1
This file doesn't exist at all: cluster_trj/3/assignment.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/3/assignment.dat, file_b: cluster_trj/3/assignment.dat, errors:-1
This file doesn't exist at all: cluster_trj/3/cluster1/lifetime.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/3/cluster1/lifetime.dat, file_b: cluster_trj/3/cluster1/lifetime.dat, errors:-1
This file doesn't exist at all: cluster_trj/3/cluster1/average_map.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/3/cluster1/average_map.dat, file_b: cluster_trj/3/cluster1/average_map.dat, errors:-1
This file doesn't exist at all: cluster_trj/3/cluster0/lifetime.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/3/cluster0/lifetime.dat, file_b: cluster_trj/3/cluster0/lifetime.dat, errors:-1
This file doesn't exist at all: cluster_trj/3/cluster0/average_map.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/3/cluster0/average_map.dat, file_b: cluster_trj/3/cluster0/average_map.dat, errors:-1
This file doesn't exist at all: cluster_trj/3/cluster2/lifetime.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/3/cluster2/lifetime.dat, file_b: cluster_trj/3/cluster2/lifetime.dat, errors:-1
This file doesn't exist at all: cluster_trj/3/cluster2/average_map.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/3/cluster2/average_map.dat, file_b: cluster_trj/3/cluster2/average_map.dat, errors:-1
This file doesn't exist at all: cluster_trj/1/assignment.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/1/assignment.dat, file_b: cluster_trj/1/assignment.dat, errors:-1
This file doesn't exist at all: cluster_trj/1/cluster0/lifetime.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/1/cluster0/lifetime.dat, file_b: cluster_trj/1/cluster0/lifetime.dat, errors:-1
This file doesn't exist at all: cluster_trj/1/cluster0/average_map.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_trj/1/cluster0/average_map.dat, file_b: cluster_trj/1/cluster0/average_map.dat, errors:-1
Test 3: Framewise cluster analysis.... FAILED
This file doesn't exist at all: cluster_res/lifetime/2/assignment.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_res/lifetime/2/assignment.dat, file_b: cluster_res/lifetime/2/assignment.dat, errors:-1
This file doesn't exist at all: cluster_res/lifetime/3/assignment.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_res/lifetime/3/assignment.dat, file_b: cluster_res/lifetime/3/assignment.dat, errors:-1
This file doesn't exist at all: cluster_res/lifetime/1/assignment.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_res/lifetime/1/assignment.dat, file_b: cluster_res/lifetime/1/assignment.dat, errors:-1
This file doesn't exist at all: cluster_res/distance/2/assignment.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_res/distance/2/assignment.dat, file_b: cluster_res/distance/2/assignment.dat, errors:-1
This file doesn't exist at all: cluster_res/distance/3/assignment.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_res/distance/3/assignment.dat, file_b: cluster_res/distance/3/assignment.dat, errors:-1
This file doesn't exist at all: cluster_res/distance/1/assignment.dat. This probably means that CONAN could not run at all.
file_a: correct_output/cluster_res/distance/1/assignment.dat, file_b: cluster_res/distance/1/assignment.dat, errors:-1
Test 4: Residue-wise cluster analysis.... FAILED
This file doesn't exist at all: blocking/block_out.txt. This probably means that CONAN could not run at all.
file_a: correct_output/blocking/block_out.txt, file_b: blocking/block_out.txt, errors:-1
Test 5: Blocking analysis.... FAILED
This file doesn't exist at all: pca/pc.9.dat. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pc.9.dat, file_b: pca/pc.9.dat, errors:-1
This file doesn't exist at all: pca/pc.10.dat. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pc.10.dat, file_b: pca/pc.10.dat, errors:-1
This file doesn't exist at all: pca/pca_output.txt. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pca_output.txt, file_b: pca/pca_output.txt, errors:-1
This file doesn't exist at all: pca/pc.5.dat. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pc.5.dat, file_b: pca/pc.5.dat, errors:-1
This file doesn't exist at all: pca/pc.3.dat. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pc.3.dat, file_b: pca/pc.3.dat, errors:-1
This file doesn't exist at all: pca/pca_projections.dat. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pca_projections.dat, file_b: pca/pca_projections.dat, errors:-1
This file doesn't exist at all: pca/pc.6.dat. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pc.6.dat, file_b: pca/pc.6.dat, errors:-1
This file doesn't exist at all: pca/pc.8.dat. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pc.8.dat, file_b: pca/pc.8.dat, errors:-1
This file doesn't exist at all: pca/pc.4.dat. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pc.4.dat, file_b: pca/pc.4.dat, errors:-1
This file doesn't exist at all: pca/pc.2.dat. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pc.2.dat, file_b: pca/pc.2.dat, errors:-1
This file doesn't exist at all: pca/pc.1.dat. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pc.1.dat, file_b: pca/pc.1.dat, errors:-1
This file doesn't exist at all: pca/pc.7.dat. This probably means that CONAN could not run at all.
file_a: correct_output/pca/pc.7.dat, file_b: pca/pc.7.dat, errors:-1
Test 6: Principal component analysis.... FAILED
This file doesn't exist at all: matrices/00005_dr.prev.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00005_dr.prev.dat, file_b: matrices/00005_dr.prev.dat, errors:-1
This file doesn't exist at all: matrices/00002_dr.prev.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00002_dr.prev.dat, file_b: matrices/00002_dr.prev.dat, errors:-1
This file doesn't exist at all: matrices/00006_dr.prev.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00006_dr.prev.dat, file_b: matrices/00006_dr.prev.dat, errors:-1
This file doesn't exist at all: matrices/00010.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00010.dat, file_b: matrices/00010.dat, errors:-1
This file doesn't exist at all: matrices/00001_dr.init.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00001_dr.init.dat, file_b: matrices/00001_dr.init.dat, errors:-1
This file doesn't exist at all: matrices/00001_dr.prev.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00001_dr.prev.dat, file_b: matrices/00001_dr.prev.dat, errors:-1
This file doesn't exist at all: matrices/00005_dr.init.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00005_dr.init.dat, file_b: matrices/00005_dr.init.dat, errors:-1
This file doesn't exist at all: matrices/00010_dr.prev.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00010_dr.prev.dat, file_b: matrices/00010_dr.prev.dat, errors:-1
This file doesn't exist at all: matrices/00004_dr.prev.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00004_dr.prev.dat, file_b: matrices/00004_dr.prev.dat, errors:-1
This file doesn't exist at all: matrices/00004_dr.init.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00004_dr.init.dat, file_b: matrices/00004_dr.init.dat, errors:-1
This file doesn't exist at all: matrices/00008.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00008.dat, file_b: matrices/00008.dat, errors:-1
This file doesn't exist at all: matrices/00009_dr.prev.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00009_dr.prev.dat, file_b: matrices/00009_dr.prev.dat, errors:-1
This file doesn't exist at all: matrices/00010_dr.init.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00010_dr.init.dat, file_b: matrices/00010_dr.init.dat, errors:-1
This file doesn't exist at all: matrices/00000.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00000.dat, file_b: matrices/00000.dat, errors:-1
This file doesn't exist at all: matrices/00007_dr.init.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00007_dr.init.dat, file_b: matrices/00007_dr.init.dat, errors:-1
This file doesn't exist at all: matrices/00003_dr.prev.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00003_dr.prev.dat, file_b: matrices/00003_dr.prev.dat, errors:-1
This file doesn't exist at all: matrices/00006.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00006.dat, file_b: matrices/00006.dat, errors:-1
This file doesn't exist at all: matrices/00005.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00005.dat, file_b: matrices/00005.dat, errors:-1
This file doesn't exist at all: matrices/00007_dr.prev.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00007_dr.prev.dat, file_b: matrices/00007_dr.prev.dat, errors:-1
This file doesn't exist at all: matrices/00002.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00002.dat, file_b: matrices/00002.dat, errors:-1
This file doesn't exist at all: matrices/00001.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00001.dat, file_b: matrices/00001.dat, errors:-1
This file doesn't exist at all: matrices/00009_dr.init.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00009_dr.init.dat, file_b: matrices/00009_dr.init.dat, errors:-1
This file doesn't exist at all: matrices/00006_dr.init.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00006_dr.init.dat, file_b: matrices/00006_dr.init.dat, errors:-1
This file doesn't exist at all: matrices/00008_dr.init.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00008_dr.init.dat, file_b: matrices/00008_dr.init.dat, errors:-1
This file doesn't exist at all: matrices/00008_dr.prev.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00008_dr.prev.dat, file_b: matrices/00008_dr.prev.dat, errors:-1
This file doesn't exist at all: matrices/00009.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00009.dat, file_b: matrices/00009.dat, errors:-1
This file doesn't exist at all: matrices/00003.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00003.dat, file_b: matrices/00003.dat, errors:-1
This file doesn't exist at all: matrices/00003_dr.init.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00003_dr.init.dat, file_b: matrices/00003_dr.init.dat, errors:-1
This file doesn't exist at all: matrices/00007.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00007.dat, file_b: matrices/00007.dat, errors:-1
This file doesn't exist at all: matrices/00004.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00004.dat, file_b: matrices/00004.dat, errors:-1
This file doesn't exist at all: matrices/00002_dr.init.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00002_dr.init.dat, file_b: matrices/00002_dr.init.dat, errors:-1
Test 7: Rereading of sparse files.... FAILED
This file doesn't exist at all: aggregate/time_mdmat_rmsd.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/time_mdmat_rmsd.dat, file_b: aggregate/time_mdmat_rmsd.dat, errors:-1
This file doesn't exist at all: aggregate/total_interactions.y.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/total_interactions.y.dat, file_b: aggregate/total_interactions.y.dat, errors:-1
This file doesn't exist at all: aggregate/timeline.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/timeline.dat, file_b: aggregate/timeline.dat, errors:-1
This file doesn't exist at all: aggregate/native_contacts.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/native_contacts.dat, file_b: aggregate/native_contacts.dat, errors:-1
This file doesn't exist at all: aggregate/mdmat_average_rmsf.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/mdmat_average_rmsf.dat, file_b: aggregate/mdmat_average_rmsf.dat, errors:-1
This file doesn't exist at all: aggregate/total_interactions.x.dat. This probably means that CONAN could not run at all.
file_a: correct_output/aggregate/total_interactions.x.dat, file_b: aggregate/total_interactions.x.dat, errors:-1
This file doesn't exist at all: matrices/00010.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00010.dat, file_b: matrices/00010.dat, errors:-1
This file doesn't exist at all: matrices/00008.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00008.dat, file_b: matrices/00008.dat, errors:-1
This file doesn't exist at all: matrices/00000.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00000.dat, file_b: matrices/00000.dat, errors:-1
This file doesn't exist at all: matrices/00006.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00006.dat, file_b: matrices/00006.dat, errors:-1
This file doesn't exist at all: matrices/00005.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00005.dat, file_b: matrices/00005.dat, errors:-1
This file doesn't exist at all: matrices/00002.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00002.dat, file_b: matrices/00002.dat, errors:-1
This file doesn't exist at all: matrices/00001.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00001.dat, file_b: matrices/00001.dat, errors:-1
This file doesn't exist at all: matrices/00009.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00009.dat, file_b: matrices/00009.dat, errors:-1
This file doesn't exist at all: matrices/00003.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00003.dat, file_b: matrices/00003.dat, errors:-1
This file doesn't exist at all: matrices/00007.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00007.dat, file_b: matrices/00007.dat, errors:-1
This file doesn't exist at all: matrices/00004.dat. This probably means that CONAN could not run at all.
file_a: correct_output/matrices/00004.dat, file_b: matrices/00004.dat, errors:-1
Test 8: Asymmetric mode.... FAILED
7 test(s) failed. The output of the failed tests has been preserved.
It is possible that the deviations are minor.
The failures are in the following folders:
2_Pearson
3_ClusterTraj
4_ClusterRes
5_Blocking
6_PCA
7_Reread
8_Asymmetric

**Comment by csabadaday** [comment]
Hi Mattyboi123,

Ironically, the test module is the one that causes the most problems. :( 

Could you tell me if this is from the "stable" version 1.0 or the newest commit? The "stable" version's (gulp) test module crashes on zsh but not on bash. I'd suggest you clone the newest commit and just use it, it should work on all Linux shells.

A simpler way would be to just not run the test script. Chances are, conan works just fine, it is the test script's interactions with Linux that fail.

Let me know if this helped and sorry for the inconvenience.

Csaba

**Comment by Mattyboi123** [comment]
Hi, I'll need to check which version it is, it was the one on git? the
machine I'm trying to run on had very little already installed - not even
numpy. I decided to cut my losses on the tests and went ahead and tried to
run the ubiquitin unfolding tutorial having installed a numpy version
which supports nosetesting as that was required. now the error is returned

Gromacs executable was not found
Will create the following number of clusters of frames: 1 2 3 4 5
sh: 1: mdmat: not found
Traceback (most recent call last):
  File "../../conan.py", line 1786, in <module>
    inputf = open('dmf.xpm')
FileNotFoundError: [Errno 2] No such file or directory: 'dmf.xpm'

I thought this might be to do with the verson of gromacs that I have being
2019 and the syntax I have to use to call any gmx function, 'gmx_2019
<function>' so  I was just about to skry conan.py and replace all of the
instances of 'gmx' with 'gmx_2019' and function calls of gmx like 'mdmat'
with 'gmx_2019 mdmat' to see if that worked. I'd take any advice though!

**Comment by csabadaday** [comment]
It's best if you install the newest anaconda distribution, it's very practical also for other uses.

Yes I think if you replace "gmx" with "gmx_2019" that will work. Or just add
alias gmx='gmx_2019'
in your ./.bashrc file.

**Comment by Mattyboi123** [comment]
when you say my bashrc file..what do you mean? just at the start of the
input fille?

**Comment by Mattyboi123** [comment]
I see what bashrc is now, I was unable to make an alias stick, but there
was only one instance of gmx in conan.py and changing it to gmx_2019 was
sufficient to get the script to run - incredible useful package thanks a
lot!

**Comment by Mattyboi123** [comment]
although its now running on my simulation  I get this error at the end


hierarchical...
Traceback (most recent call last):
  File "../../conan.py", line 2090, in <module>
    call_hierarchical('cluster_trj', vectors, trunc, trunc_inter,
rmsd_interframe_cond, nframes, ks_traj, 'Trajectory', time_vec, 'trj',
xterm, xres, yterm, yres, asymm, matrices)
  File "../../conan.py", line 1370, in call_hierarchical
    plt.figure(figsize=(25, 10))
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 539, in
figure
    **kwargs)
  File "/usr/lib/python3/dist-packages/matplotlib/backend_bases.py", line
171, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File
"/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py", line
1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2023, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive,
wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

but I'm not sure what it isn't doing.

**Comment by csabadaday** [comment]
Hey,

I am not sure either. Could you install an anaconda distribution? It is a python distribution with all packages up to date etc.

Alternatively, assuming you don't want to do any cluster analysis, you can just go on like this. matplotlib is only called there.

Hope this helps!

Csaba

**Comment by Mattyboi123** [comment]
yes I've done so now, still having some issues but I'll keep at it for a bit
